[package]
name = "music-player"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
gio = "0.15.10"
gtk = "0.15.4"
gdk-pixbuf = "0.15.10"
id3 = "1.0.2"
gtk-sys = "0.15.3"